### ISSUE TITLE
入行前端一年经验与体会

### ISSUE THREAD

**Issue by liangfengbo** [liangfengbo/frontend-develop#3]
### 一、什么是前端？

我个人对前端的定义更为容易表达的是：不断地做出更好看的视觉页面、更加人性化的功能，提供给用户使用。

### 二、什么是好前端？

我现在的能力理解好的前端有：

第一：写一个页面容易，写好一个页面非常难，如何把设计师的设计稿高清还原出来，每个块的间距，每个字体大小，宽高度适配，移动端和PC端的代码如何做到耦合性，高复用，以及css的命名规范，等等，想写好一个页面真的非常难，以及耗脑子，当然我现在也不断的打好css的基础。

推荐学习资源，当然我不是托，我现在是分享一些好的学习资源，也可以自己上w3c官网看文档

[mozilla.org文档](https://developer.mozilla.org/zh-CN/)

[前端团队的代码规范](https://github.com/Yunkou/FE-code-style)

[如何在Vue项目中使用vw实现移动端适配](https://www.w3cplus.com/mobile/vw-layout-in-vue.html)

[慕课网全面系统讲解CSS 工作应用+面试一步搞定 ](https://coding.imooc.com/class/164.html)

第二、是解决问题的能力，任何bug都有它的原因，遇到问题时，静下来细心想想哪步出错了，或我自己没有搞懂原理呢？发现bug，自己solve the problem，才是提升自己。

第三、学习的能力，前端更新那么快，多得像大海茫茫的一片。重要的还是回归基础，打扎实基础，业务开发需求需要技术信手沾来。

### 三、前端后端？深度广度？

做前端的要不要学后端啊？要不要做全栈啊？我前端感觉好多东西要学啊，好像又提不高？

之前我有看过一篇阿里工程师写的一篇文章，技术是用来解决问题的，那用什么技术解决问题这是一个不多深究的问题，重要的是思想，前面提到的解决问题的能力，那么做前端的要不要学后端啊？要不要做全栈啊？这个就要问你自己的实际结合起来了，我个人技术路线是先精后广。

推荐一篇文章：七月老师的

[追寻本质还是流于形式
](https://mp.weixin.qq.com/s/ga6I2hLWRRJ9i1wjD39ROg)

### 四、总结自己的前端职业发展。

我工作一年了，最大的收获是提升了自己的阅读文档能力，也培养了自己的一些开发思维和解决问题的能力，但远远还不够，我希望我18年能继续打扎实基础，技术栈路线： html，css，js，vuejs，nodejs，webpack。

**Comment by wmguitar** [comment]
good~~~

**Comment by liangfengbo** [comment]
7月，不平凡，我报考了华工自考，和下决心学习数据结构与算法，希望我在计算机这道路会走得更远。

**Comment by Joyboo** [comment]
波波加油
